loc_names = [
    "on the floor",
    "on the chair",
    "on the table",
    "on the sofa",
    "on the bookshelf",
    "on the window sill",
    "on the bed",
    "on the kitchen counter",
    "on the coffee table",
    "on the TV stand",
    "on the stair",
    "on the desk",
    "on the computer keyboard",
    "in the sink",
    "on the bathtub",
    "on the piano bench",
    "inside a shoe",
    "on the rug",
    "on the dog's bed",
    "on top of the fridge",
    "inside the cereal box",
    "in a cup of coffee",
    "under the couch",
    "in the plant pot",
    "on the book",
    "under the bed",
    "in the laundry basket",
    "on the nightstand",
    "in the cat's food dish",
    "on the hat rack",
    "under the pillows",
    "on the patio",
    "in the mailbox",
    "in the bird's cage",
    "on the nachos",
    "inside the lampshade",
    "in the fireplace",
    "under the TV remote",
    "in the toaster",
    "on the bathroom counter",
    "inside the microwave",
    "on the dining table",
    "under the rug",
    "on the deck",
    "inside the oven",
    "on the grill",
    "in the pool",
    "under the kitchen sink",
    "in the closet",
    "on the lawn",
    "in the trash can",
    "on the porch swing",
    "inside the fridge",
    "on the car's dashboard",
    "in the bird bath",
    "on the roof",
    "in the garden",
    "on the treadmill",
    "in the fish tank",
    "inside the cookie jar",
    "in the glove box",
    "on the hammock",
    "in the BBQ grill",
    "on the window ledge",
    "in the rain gutter",
    "on the ceiling fan",
    "in the doll house",
    "on the swing set",
    "in the sandbox",
    "on the bicycle seat",
    "inside the mailbox",
    "on the garage floor",
    "in the cooler",
    "on the picnic table",
    "in the bird feeder",
    "on the garden bench",
    "in the tool box",
    "on the porch railing",
    "inside the washing machine",
    "on the laptop keyboard",
    "in the dog house",
    "on the trampoline",
    "in the baby's crib",
    "on the dresser",
    "inside the pantry",
    "on the mantel",
    "in the wine rack",
    "on the coat rack",
    "inside the bread box",
    "on the cat tower",
    "in the vegetable drawer",
    "on the piano keys",
    "inside the spice rack",
    "on the shower head",
    "in the flower pot",
    "on the pool float",
    "in the candy dish",
    "on the yoga mat",
    "inside the guitar case",
    "on the dartboard",
    "in the popcorn bowl"
]

warp_rift_events = [
"Orbital Debris: A piece of space debris falls onto the battlefield, providing cover in an unexpected location.",
"Comms Jammed: For one turn, units are unable to receive orders from their commander, disrupting strategies that rely heavily on command abilities.",
"Ammo Shortage: For a brief period, one of your units faces an ammo shortage. This unit's shooting attacks temporarily have their range or damage slightly reduced.",
"Unexpected Allies: A small neutral faction unit suddenly appears on the battlefield. They will attack the nearest units, regardless of which side they belong to.",
"Psyker Feedback: A psyker's power backfires, causing minor damage to themselves but not enough to take them out of the game.",
"Unstable Terrain: A section of the battlefield becomes unstable. Units that cross it must take additional time or risk falling and taking damage.",
"War Fog: A heavy fog rolls in, reducing visibility and thus reducing the effective range of ranged attacks for a turn.",
"Equipment Malfunction: A unit's equipment temporarily malfunctions, reducing its movement or attack power for a turn.",
"Imperial Probe: A small Imperial probe droid scans the area, revealing hidden units or providing slight boosts to ballistic skill for a turn.",
"Rallying Cry: One of your characters gives a rousing speech, boosting the morale of your units and providing a temporary bonus to Leadership checks.",
]